defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: ubuntu:xenial
      environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: apt update && apt install -y snapcraft
      - run:
          name: Build snap
          command: snapcraft
      - persist_to_workspace:
          root: ~/workspace
          paths: ['*.snap']

  release:
    <<: *defaults
    steps:
      - run:
          name: Install prerequisites
          command: apt update && apt install -y ca-certificates

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Push/release snap
          command: ls

workflows:
  version: 2
  commit:
    jobs:
      - build
      - release:
          requires: [build]
          filters:
            branches:
              only: master
