version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
        environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
    steps:
      - checkout
      - run:
          name: Install snapcraft
          command: apt update && apt install -y snapcraft
      - run:
          name: Build snap
          command: snapcraft
      - store_artifacts:
          path: '*.snap'
