version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: ubuntu:xenial
        environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: apt update && apt install -y snapcraft

      - run:
          name: Build snap
          command: snapcraft

      - persist_to_workspace:
          root: ~/workspace
          paths: ['*.snap']

  release:
    working_directory: ~/workspace
    # Virtual machine instead of docker because we need to install a snap,
    # which doesn't run in docker.
    machine: true
    environment:
      PATH: $PATH:/snap/bin
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            sudo apt update
            sudo apt install -y openssl snapd
            sudo snap install --beta --classic snapcraft

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Decrypt credentials
          command: |
            openssl aes-256-cbc -d \
              -in .circleci/credentials.enc \
              -out credentials \
              -k $SNAPCRAFT_CREDENTIALS_KEY

      - run:
          name: Push/release snap
          command: |
            snapcraft login --with credentials
            snapcraft push *.snap --release edge

workflows:
  version: 2
  commit:
    jobs:
      - build
      - release:
          requires: [build]
          filters:
            branches:
              only: master
